"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T09:23:06.264532+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
import argparse
import json
import os
from datetime import datetime, timezone

from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    avg,
    broadcast,
    col,
    count,
    countDistinct,
    lit,
    max as spark_max,
    min as spark_min,
    row_number,
    sum as spark_sum,
    when,
)
from pyspark.sql.types import DateType, FloatType, StringType
from pyspark.sql.window import Window


def log_row_count(stage_name: str, df):
    count_value = df.count()
    print(f"[ROW_COUNT] {stage_name}: {count_value:,} rows")


def safe_run(stage_name: str, fn, *args, **kwargs):
    try:
        return fn(*args, **kwargs)
    except Exception as exc:
        print(f"[ERROR] {stage_name} failed: {type(exc).__name__}: {exc}")
        raise


def get_args():
    parser = argparse.ArgumentParser(description="Run the Sigma DataTech pipeline")
    parser.add_argument("--input-path", default=os.getenv("INPUT_PATH", "s3://sigma-datatech/raw/transactions/"))
    parser.add_argument("--merchants-path", default=os.getenv("MERCHANTS_PATH", "s3://sigma-datatech/raw/merchants/"))
    parser.add_argument("--bronze-path", default=os.getenv("BRONZE_OUTPUT_PATH", "pipeline_brain/bronze/"))
    parser.add_argument("--silver-path", default=os.getenv("SILVER_OUTPUT_PATH", "pipeline_brain/silver/"))
    parser.add_argument("--gold-path", default=os.getenv("GOLD_OUTPUT_PATH", "pipeline_brain/gold/"))
    parser.add_argument("--metadata-dir", default=os.getenv("METADATA_OUTPUT_PATH", "pipeline_brain/"))
    parser.add_argument("--run-date", default=os.getenv("RUN_DATE", datetime.now(timezone.utc).strftime("%Y-%m-%d")))
    parser.add_argument("--run-id", default=os.getenv("RUN_ID", f"run_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}"))
    return parser.parse_args()


def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.option("header", "true")
                      .option("inferSchema", "false")
                       .csv(input_path)
                      .withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))
    
    merchants_df = (spark.read.option("header", "true")
                     .option("inferSchema", "false")
                    .csv(merchants_path)
                    .withColumn("ingestion_timestamp", lit(run_date))
                    .withColumn("source_file", lit("merchants.csv"))
                    .withColumn("pipeline_run_id", lit(run_id)))
    
    # Write as Parquet partitioned by date
    transactions_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(os.path.join(output_path, "transactions"))
    merchants_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(os.path.join(output_path, "merchants"))

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.parquet(bronze_path)
                      .where(col("ingestion_timestamp") == run_date))
    
    merchants_df = (spark.read.parquet(merchants_path)
                   .where(col("ingestion_timestamp") == run_date)
                    .cache())  # Cache the small merchants table
    
    # Cast columns to correct types
    transactions_df = transactions_df.withColumn("amount", col("amount").cast(FloatType()))
    transactions_df = transactions_df.withColumn("transaction_date", col("transaction_date").cast(DateType()))
    transactions_df = transactions_df.withColumn("transaction_id", col("transaction_id").cast(StringType()))
    transactions_df = transactions_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))

    log_row_count("Silver after cast", transactions_df)

    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    log_row_count("Silver after filter", transactions_df)

    dedup_window = Window.partitionBy("transaction_id").orderBy(col("ingestion_timestamp").desc())
    transactions_df = (
        transactions_df.withColumn("row_number", row_number().over(dedup_window))
        .filter(col("row_number") == 1)
        .drop("row_number")
    )
    log_row_count("Silver after deduplication", transactions_df)

    transactions_df = (transactions_df.join(broadcast(merchants_df), "merchant_id", "left")
                      .withColumn("quality_flag", 
                                  when(col("merchant_id").isNull(), "UNMATCHED").otherwise("CLEAN")))
    log_row_count("Silver after enrichment", transactions_df)

    # Write as Parquet partitioned by date
    transactions_df.write.mode("overwrite").partitionBy("transaction_date").parquet(output_path)

def main():
    args = get_args()

    spark = (SparkSession.builder
             .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())

    safe_run(
        "Ingest Bronze",
        ingest_bronze,
        spark,
        args.input_path,
        args.merchants_path,
        args.bronze_path,
        args.run_date,
        args.run_id,
    )

    safe_run(
        "Transform Silver",
        transform_silver,
        spark,
        os.path.join(args.bronze_path, "transactions"),
        os.path.join(args.bronze_path, "merchants"),
        args.silver_path,
        args.run_date,
    )

    safe_run(
        "Build Gold",
        run_gold,
        spark,
        args.silver_path,
        args.gold_path,
        args.run_date,
    )

    os.makedirs(args.metadata_dir, exist_ok=True)
    report_path = os.path.join(args.metadata_dir, f"run_metadata_{args.run_date}.json")
    run_metadata = {"run_date": args.run_date, "run_id": args.run_id, "status": "SUCCESS"}
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump(run_metadata, f)
    print(f"[OUTPUT] Saved run metadata to {report_path}")

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate metrics
    merchant_performance_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(
            spark_sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write to Gold layer
    merchant_performance_df.write.mode("overwrite").partitionBy("date").parquet(output_path + "/merchant_performance")

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    completed_df = silver_df.filter(col("status") == "COMPLETED")
    
    customer_ltv_df = completed_df.groupBy("customer_id").agg(
        spark_sum("amount").alias("total_spent"),
        count("*").alias("total_txns"),
        avg("amount").alias("avg_txn_value"),
        spark_min("transaction_date").alias("first_txn_date"),
        spark_max("transaction_date").alias("last_txn_date"),
    )

    preferred_method = (
        completed_df.groupBy("customer_id", "payment_method")
        .agg(count("*").alias("method_count"))
        .withColumn("row_number", row_number().over(Window.partitionBy("customer_id").orderBy(col("method_count").desc(), col("payment_method"))))
        .filter(col("row_number") == 1)
        .select("customer_id", col("payment_method").alias("preferred_payment_method"))
    )

    customer_ltv_df = customer_ltv_df.join(preferred_method, "customer_id", "left")
    customer_ltv_df.write.mode("overwrite").parquet(output_path + "/customer_ltv")

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate metrics
    daily_summary_df = silver_df.groupBy("date") \
        .agg(
            spark_sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
            count("*").alias("total_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )
    
    # Write to Gold layer
    daily_summary_df.write.mode("overwrite").partitionBy("date").parquet(output_path + "/daily_summary")

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Build Gold layer tables
    build_merchant_performance(spark, silver_path, gold_output_dir, run_date)
    build_customer_ltv(spark, silver_path, gold_output_dir)
    build_daily_summary(spark, silver_path, gold_output_dir, run_date)
    
    # Write run metadata
    run_metadata = {
        "run_date": run_date,
        "silver_path": silver_path,
        "gold_output_dir": gold_output_dir,
        "status": "success"
    }
    spark.sparkContext.parallelize([run_metadata]).write.json(gold_output_dir + "/run_metadata")

if __name__ == "__main__":
    spark = SparkSession.builder.appName("Sigma DataTech Transaction Analytics Pipeline").getOrCreate()
    silver_path = "s3://path/to/silver/"
    gold_output_dir = "s3://path/to/gold/"
    run_date = "2026-05-27"
    
    run_gold(spark, silver_path, gold_output_dir, run_date)
